name: yoga
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  video_player: 2.9.2
  youtube_player_iframe: ^5.2.2
  flutter_inappwebview: ^6.1.5
  shimmer: ^3.0.0
  google_mlkit_pose_detection: ^0.14.0
  http: ^1.1.0
  tflite_flutter: ^0.12.1
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.0.7
  youtube_player_flutter: 9.1.3
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.0.0
  ffmpeg_kit_flutter_new_full: 2.0.0
  youtube_explode_dart: ^2.0.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  google_generative_ai: ^0.2.0
  device_preview: ^1.1.0
  image: ^4.5.4
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assests/
    - assests/vedio/
    - assests/yoga_black_icon.svg


  
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assests/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
    - family: open_sans
      fonts:
       - asset: assests/fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf

    - family : OFL
      fonts:
        - asset: assests/fonts/Kalam-Bold.ttf
    - family : Lora
      fonts:
        - asset : assests/fonts/Lora-Italic-VariableFont_wght.ttf